apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - image: alpine
        name: cm-container
        command: ['sh', '-c', 'while true; do echo $NAME; sleep 1; done']
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: name
